%\VignetteIndexEntry{Segmentation demo}
%\VignetteDepends{tilingArray}
%\VignettePackage{tilingArray}

% ---- This is just a stub. -----
% The real .Rnw source for this vignette is in inst/scripts/segmentation.Rnw
% It cannot be put here (inst/doc/) since it takes too much time and memory to run.
% So it needs to be run manually, and the resulting PDF is distributed as part 
% of the source package. See the 'Makefile' in this directory, which will 
% copy the PDF from ../scripts to here.

\documentclass[11pt]{article}
\begin{document}
\end{document}

